[pytest]

addopts = -v --cov=models.user_model --cov=controllers --cov=services --cov=config --cov-report=term-missing --cov-fail-under=80



#o -v serve para mostrar no arquivo quais são as funções que foram utilizadas no arquivo de teste -v = verbose